- Effect: Allow
  Action:
    - connect:*
  Resource: arn:aws:connect:ap-southeast-2:<AWS Account Id>:instance/*
- Effect: Allow
  Action:
    - kinesis:*
  Resource: arn:aws:kinesis:ap-southeast-2:<AWS Account Id>:stream/<stream name>-${self:custom.env}